#!/bin/bash
# Auto-generated package install script
# Source machine: Ubuntu 20.04 Focal (~3111 packages)

set -e

echo "Updating apt sources..."
sudo apt-get update

PACKAGES=(
  accountsservice-ubuntu-schemas
  accountsservice
  acl
  acpi-support
  acpid
  adduser
  adwaita-icon-theme
  aisleriot
  alsa-base
  alsa-topology-conf
  alsa-ucm-conf
  alsa-utils
  amd64-microcode
  anacron
  apg
  app-install-data-partner
  apparmor
  apport-gtk
  apport-symptoms
  apport
  appstream
  apt-config-icons-hidpi
  apt-config-icons
  apt-transport-https
  apt-utils
  apt
  aptdaemon-data
  aptdaemon
  apturl-common
  apturl
  aspell-en
  aspell
  at-spi2-core
  at
  autoconf
  automake
  autopoint
  autotools-dev
  avahi-autoipd
  avahi-daemon
  avahi-utils
  baobab
  base-files
  base-passwd
  bash-completion
  bash
  bc
  bcache-tools
  bind9-dnsutils
  bind9-host
  bind9-libs
  binfmt-support
  binutils-common
  binutils-x86-64-linux-gnu
  binutils
  blt
  bluez-cups
  bluez-obexd
  bluez
  bolt
  branding-ubuntu
  brltty
  brz
  bsdmainutils
  bsdutils
  btrfs-progs
  bubblewrap
  build-essential
  busybox-initramfs
  busybox-static
  byobu
  bzip2-doc
  bzip2
  bzr
  ca-certificates-java
  ca-certificates
  cheese-common
  cheese
  clang-10
  clang-8
  cloud-guest-utils
  cloud-init
  cloud-initramfs-copymods
  cloud-initramfs-dyn-netconf
  cmake-data
  cmake
  code
  colord-data
  colord
  comerr-dev
  command-not-found
  console-setup-linux
  console-setup
  coreutils
  cpio
  cpp-7
  cpp-8
  cpp-9
  cpp
  cracklib-runtime
  crda
  cron
  cryptsetup-bin
  cryptsetup-initramfs
  cryptsetup-run
  cryptsetup
  cuda-drivers-535
  cuda-drivers
  cuda-keyring
  cups-browsed
  cups-bsd
  cups-client
  cups-common
  cups-core-drivers
  cups-daemon
  cups-filters-core-drivers
  cups-filters
  cups-ipp-utils
  cups-pk-helper
  cups-ppdc
  cups-server-common
  cups
  curl
  cython3
  dash
  dbus-user-session
  dbus-x11
  dbus
  dc
  dconf-cli
  dconf-gsettings-backend
  dconf-service
  dctrl-tools
  debconf-i18n
  debconf
  debhelper
  debianutils
  default-libmysqlclient-dev
  deja-dup
  desktop-base
  desktop-file-utils
  dh-autoreconf
  dh-strip-nondeterminism
  dictionaries-common
  diffutils
  dirmngr
  distro-info-data
  distro-info
  dkms
  dmeventd
  dmidecode
  dmsetup
  dmz-cursor-theme
  dns-root-data
  dnsmasq-base
  docbook-xml
  docutils-common
  dosfstools
  dpkg-dev
  dpkg-sig
  dpkg
  duplicity
  dwz
  e2fsprogs
  eatmydata
  ec2-hibinit-agent
  ec2-instance-connect
  ed
  efibootmgr
  eject
  elementary-xfce-icon-theme
  emacsen-common
  enchant-2
  eog
  espeak-ng-data
  ethtool
  evemu-tools
  evince-common
  evince
  evolution-data-server-common
  evolution-data-server
  evtest
  exo-utils
  fakeroot
  fdisk
  file-roller
  file
  finalrd
  findutils
  firefox
  fltk1.3-doc
  fluid
  fontconfig-config
  fontconfig
  fonts-beng-extra
  fonts-beng
  fonts-dejavu-core
  fonts-dejavu-extra
  fonts-deva-extra
  fonts-deva
  fonts-droid-fallback
  fonts-freefont-ttf
  fonts-gargi
  fonts-gubbi
  fonts-gujr-extra
  fonts-gujr
  fonts-guru-extra
  fonts-guru
  fonts-indic
  fonts-kacst-one
  fonts-kacst
  fonts-kalapi
  fonts-khmeros-core
  fonts-knda
  fonts-lao
  fonts-lato
  fonts-liberation2
  fonts-liberation
  fonts-lklug-sinhala
  fonts-lohit-beng-assamese
  fonts-lohit-beng-bengali
  fonts-lohit-deva
  fonts-lohit-gujr
  fonts-lohit-guru
  fonts-lohit-knda
  fonts-lohit-mlym
  fonts-lohit-orya
  fonts-lohit-taml-classical
  fonts-lohit-taml
  fonts-lohit-telu
  fonts-lyx
  fonts-mlym
  fonts-nakula
  fonts-navilu
  fonts-noto-cjk
  fonts-noto-color-emoji
  fonts-noto-mono
  fonts-opensymbol
  fonts-orya-extra
  fonts-orya
  fonts-pagul
  fonts-quicksand
  fonts-sahadeva
  fonts-samyak-deva
  fonts-samyak-gujr
  fonts-samyak-mlym
  fonts-samyak-taml
  fonts-sarai
  fonts-sil-abyssinica
  fonts-sil-padauk
  fonts-smc-anjalioldlipi
  fonts-smc-chilanka
  fonts-smc-dyuthi
  fonts-smc-gayathri
  fonts-smc-karumbi
  fonts-smc-keraleeyam
  fonts-smc-manjari
  fonts-smc-meera
  fonts-smc-rachana
  fonts-smc-raghumalayalamsans
  fonts-smc-suruma
  fonts-smc-uroob
  fonts-smc
  fonts-taml
  fonts-telu-extra
  fonts-telu
  fonts-thai-tlwg
  fonts-tibetan-machine
  fonts-tlwg-garuda-ttf
  fonts-tlwg-garuda
  fonts-tlwg-kinnari-ttf
  fonts-tlwg-kinnari
  fonts-tlwg-laksaman-ttf
  fonts-tlwg-laksaman
  fonts-tlwg-loma-ttf
  fonts-tlwg-loma
  fonts-tlwg-mono-ttf
  fonts-tlwg-mono
  fonts-tlwg-norasi-ttf
  fonts-tlwg-norasi
  fonts-tlwg-purisa-ttf
  fonts-tlwg-purisa
  fonts-tlwg-sawasdee-ttf
  fonts-tlwg-sawasdee
  fonts-tlwg-typewriter-ttf
  fonts-tlwg-typewriter
  fonts-tlwg-typist-ttf
  fonts-tlwg-typist
  fonts-tlwg-typo-ttf
  fonts-tlwg-typo
  fonts-tlwg-umpush-ttf
  fonts-tlwg-umpush
  fonts-tlwg-waree-ttf
  fonts-tlwg-waree
  fonts-ubuntu-console
  fonts-ubuntu
  fonts-urw-base35
  fonts-yrsa-rasa
  foomatic-db-compressed-ppds
  fprintd
  freeglut3-dev
  freeglut3
  friendly-recovery
  ftp
  fuse3
  fwupd-signed
  fwupd
  g++-7
  g++-8
  g++-9
  g++
  gamemode
  gawk
  gazebo11-common
  gazebo11-plugin-base
  gazebo11
  gcc-10-base
  gcc-7-base
  gcc-7
  gcc-8-base
  gcc-8
  gcc-9-base
  gcc-9
  gcc
  gcr
  gdal-data
  gdb
  gdbserver
  gdisk
  gdm3
  gedit-common
  gedit
  genisoimage
  geoclue-2.0
  gettext-base
  gettext
  gfortran-8
  gfortran-9
  gfortran
  ghostscript-x
  ghostscript
  gimp-data
  gimp
  gir1.2-accountsservice-1.0
  gir1.2-atk-1.0
  gir1.2-atspi-2.0
  gir1.2-clutter-1.0
  gir1.2-clutter-gst-3.0
  gir1.2-cogl-1.0
  gir1.2-coglpango-1.0
  gir1.2-dbusmenu-glib-0.4
  gir1.2-dee-1.0
  gir1.2-freedesktop
  gir1.2-gck-1
  gir1.2-gcr-3
  gir1.2-gdesktopenums-3.0
  gir1.2-gdkpixbuf-2.0
  gir1.2-gdm-1.0
  gir1.2-geoclue-2.0
  gir1.2-glib-2.0
  gir1.2-gmenu-3.0
  gir1.2-gnomebluetooth-1.0
  gir1.2-gnomedesktop-3.0
  gir1.2-graphene-1.0
  gir1.2-gst-plugins-base-1.0
  gir1.2-gstreamer-1.0
  gir1.2-gtk-2.0
  gir1.2-gtk-3.0
  gir1.2-gtkclutter-1.0
  gir1.2-gtksource-4
  gir1.2-gudev-1.0
  gir1.2-gweather-3.0
  gir1.2-harfbuzz-0.0
  gir1.2-ibus-1.0
  gir1.2-javascriptcoregtk-4.0
  gir1.2-json-1.0
  gir1.2-mutter-6
  gir1.2-nm-1.0
  gir1.2-nma-1.0
  gir1.2-notify-0.7
  gir1.2-packagekitglib-1.0
  gir1.2-pango-1.0
  gir1.2-peas-1.0
  gir1.2-polkit-1.0
  gir1.2-rb-3.0
  gir1.2-rsvg-2.0
  gir1.2-secret-1
  gir1.2-snapd-1
  gir1.2-soup-2.4
  gir1.2-totem-1.0
  gir1.2-totemplparser-1.0
  gir1.2-udisks-2.0
  gir1.2-unity-5.0
  gir1.2-upowerglib-1.0
  gir1.2-vte-2.91
  gir1.2-webkit2-4.0
  gir1.2-wnck-3.0
  git-man
  git
  gjs
  gkbd-capplet
  glib-networking-common
  glib-networking-services
  glib-networking
  gnome-accessibility-themes
  gnome-bluetooth
  gnome-calculator
  gnome-calendar
  gnome-characters
  gnome-control-center-data
  gnome-control-center-faces
  gnome-control-center
  gnome-desktop3-data
  gnome-disk-utility
  gnome-font-viewer
  gnome-getting-started-docs
  gnome-initial-setup
  gnome-keyring-pkcs11
  gnome-keyring
  gnome-logs
  gnome-mahjongg
  gnome-menus
  gnome-mines
  gnome-online-accounts
  gnome-power-manager
  gnome-screensaver
  gnome-screenshot
  gnome-session-bin
  gnome-session-canberra
  gnome-session-common
  gnome-settings-daemon-common
  gnome-settings-daemon
  gnome-shell-common
  gnome-shell-extension-appindicator
  gnome-shell-extension-desktop-icons
  gnome-shell-extension-ubuntu-dock
  gnome-shell
  gnome-startup-applications
  gnome-sudoku
  gnome-system-monitor
  gnome-terminal-data
  gnome-terminal
  gnome-themes-extra-data
  gnome-themes-extra
  gnome-todo-common
  gnome-todo
  gnome-user-docs
  gnome-video-effects
  gnupg-l10n
  gnupg-utils
  gnupg1-l10n
  gnupg1
  gnupg
  google-mock
  googletest
  gpg-agent
  gpg-wks-client
  gpg-wks-server
  gpg
  gpgconf
  gpgsm
  gpgv
  graphviz
  grep
  greybird-gtk-theme
  grilo-plugins-0.3-base
  groff-base
  grub-common
  grub-efi-amd64-bin
  grub-efi-amd64-signed
  grub-gfxpayload-lists
  grub-pc-bin
  grub-pc
  grub2-common
  gsettings-desktop-schemas
  gsettings-ubuntu-schemas
  gstreamer1.0-alsa
  gstreamer1.0-clutter-3.0
  gstreamer1.0-gl
  gstreamer1.0-gtk3
  gstreamer1.0-packagekit
  gstreamer1.0-plugins-base-apps
  gstreamer1.0-plugins-base
  gstreamer1.0-plugins-good
  gstreamer1.0-pulseaudio
  gstreamer1.0-tools
  gstreamer1.0-x
  gtk-update-icon-cache
  gtk2-engines-murrine
  gtk2-engines-pixbuf
  guile-2.2-libs
  gvfs-backends
  gvfs-bin
  gvfs-common
  gvfs-daemons
  gvfs-fuse
  gvfs-libs
  gvfs
  gzip
  hddtemp
  hdf5-helpers
  hdparm
  hibagent
  hicolor-icon-theme
  hostname
  hplip-data
  hplip
  htop
  humanity-icon-theme
  hunspell-en-us
  i965-va-driver
  ibus-data
  ibus-gtk3
  ibus-gtk
  ibus-table
  ibus
  ibverbs-providers
  icu-devtools
  ignition-tools
  iio-sensor-proxy
  im-config
  indicator-applet
  indicator-application
  indicator-appmenu
  indicator-bluetooth
  indicator-common
  indicator-datetime
  indicator-keyboard
  indicator-messages
  indicator-power
  indicator-printers
  indicator-session
  indicator-sound
  info
  init-system-helpers
  init
  initramfs-tools-bin
  initramfs-tools-core
  initramfs-tools
  inputattach
  install-info
  intel-media-va-driver
  intel-microcode
  intltool-debian
  ippusbxd
  iproute2
  iptables
  iputils-ping
  iputils-tracepath
  irqbalance
  isc-dhcp-client
  isc-dhcp-common
  iso-codes
  iucode-tool
  iw
  java-common
  javascript-common
  jayatana
  joystick
  kbd
  kerneloops
  keyboard-configuration
  klibc-utils
  kmod
  kpartx
  krb5-locales
  krb5-multidev
  landscape-common
  language-selector-common
  language-selector-gnome
  laptop-detect
  less
  lib32gcc-s1
  lib32stdc++6
  libaa1
  libaacs0
  libabw-0.1-1
  libaccinj64-10.1
  libaccounts-glib0
  libaccountsservice0
  libacl1
  libaec-dev
  libaec0
  libaio1
  libalgorithm-diff-perl
  libalgorithm-diff-xs-perl
  libalgorithm-merge-perl
  libamd2
  libamtk-5-0
  libamtk-5-common
  libann0
  libao-common
  libao4
  libaom0
  libapparmor1
  libappindicator3-1
  libappstream4
  libapr1-dev
  libapr1
  libaprutil1-dev
  libaprutil1
  libapt-pkg6.0
  libarchive-cpio-perl
  libarchive-zip-perl
  libarchive13
  libargon2-1
  libarmadillo-dev
  libarmadillo9
  libarpack2-dev
  libarpack2
  libasan4
  libasan5
  libasn1-8-heimdal
  libasound2-data
  libasound2-dev
  libasound2-plugins
  libasound2
  libaspell15
  libass9
  libassimp-dev
  libassimp5
  libassuan-dev
  libassuan0
  libasyncns0
  libatasmart4
  libatk-adaptor
  libatk-bridge2.0-0
  libatk-wrapper-java-jni
  libatk-wrapper-java
  libatk1.0-0
  libatk1.0-data
  libatk1.0-dev
  libatkmm-1.6-1v5
  libatm1
  libatomic1
  libatopology2
  libatspi2.0-0
  libattr1
  libaudit-common
  libaudit1
  libauthen-sasl-perl
  libavahi-client3
  libavahi-common-data
  libavahi-common3
  libavahi-core7
  libavahi-glib1
  libavahi-ui-gtk3-0
  libavc1394-0
  libavcodec-dev
  libavcodec58
  libavdevice-dev
  libavdevice58
  libavfilter-dev
  libavfilter7
  libavformat-dev
  libavformat58
  libavresample-dev
  libavresample4
  libavutil-dev
  libavutil56
  libbabeltrace1
  libbabl-0.1-0
  libbamf3-2
  libbdplus0
  libbinutils
  libblas-dev
  libblas3
  libblkid-dev
  libblkid1
  libblockdev-crypto2
  libblockdev-fs2
  libblockdev-loop2
  libblockdev-part-err2
  libblockdev-part2
  libblockdev-swap2
  libblockdev-utils2
  libblockdev2
  libbluetooth3
  libbluray2
  libboost-all-dev
  libboost-atomic-dev
  libboost-atomic1.71-dev
  libboost-atomic1.71.0
  libboost-chrono-dev
  libboost-chrono1.71-dev
  libboost-chrono1.71.0
  libboost-container-dev
  libboost-container1.71-dev
  libboost-container1.71.0
  libboost-context-dev
  libboost-context1.71-dev
  libboost-context1.71.0
  libboost-coroutine-dev
  libboost-coroutine1.71-dev
  libboost-coroutine1.71.0
  libboost-date-time-dev
  libboost-date-time1.71-dev
  libboost-date-time1.71.0
  libboost-dev
  libboost-exception-dev
  libboost-exception1.71-dev
  libboost-fiber-dev
  libboost-fiber1.71-dev
  libboost-fiber1.71.0
  libboost-filesystem-dev
  libboost-filesystem1.71-dev
  libboost-filesystem1.71.0
  libboost-graph-dev
  libboost-graph-parallel-dev
  libboost-graph-parallel1.71-dev
  libboost-graph-parallel1.71.0
  libboost-graph1.71-dev
  libboost-graph1.71.0
  libboost-iostreams-dev
  libboost-iostreams1.71-dev
  libboost-iostreams1.71.0
  libboost-locale-dev
  libboost-locale1.71-dev
  libboost-locale1.71.0
  libboost-log-dev
  libboost-log1.71-dev
  libboost-log1.71.0
  libboost-math-dev
  libboost-math1.71-dev
  libboost-math1.71.0
  libboost-mpi-dev
  libboost-mpi-python-dev
  libboost-mpi-python1.71-dev
  libboost-mpi-python1.71.0
  libboost-mpi1.71-dev
  libboost-mpi1.71.0
  libboost-numpy-dev
  libboost-numpy1.71-dev
  libboost-numpy1.71.0
  libboost-program-options-dev
  libboost-program-options1.71-dev
  libboost-program-options1.71.0
  libboost-python-dev
  libboost-python1.71-dev
  libboost-python1.71.0
  libboost-random-dev
  libboost-random1.71-dev
  libboost-random1.71.0
  libboost-regex-dev
  libboost-regex1.71-dev
  libboost-regex1.71.0
  libboost-serialization-dev
  libboost-serialization1.71-dev
  libboost-serialization1.71.0
  libboost-stacktrace-dev
  libboost-stacktrace1.71-dev
  libboost-stacktrace1.71.0
  libboost-system-dev
  libboost-system1.71-dev
  libboost-system1.71.0
  libboost-test-dev
  libboost-test1.71-dev
  libboost-test1.71.0
  libboost-thread-dev
  libboost-thread1.71-dev
  libboost-thread1.71.0
  libboost-timer-dev
  libboost-timer1.71-dev
  libboost-timer1.71.0
  libboost-tools-dev
  libboost-type-erasure-dev
  libboost-type-erasure1.71-dev
  libboost-type-erasure1.71.0
  libboost-wave-dev
  libboost-wave1.71-dev
  libboost-wave1.71.0
  libboost1.71-dev
  libboost1.71-tools-dev
  libbrlapi0.7
  libbrotli1
  libbs2b0
  libbsd0
  libbullet-dev
  libbullet2.88
  libbz2-1.0
  libbz2-dev
  libc-bin
  libc-dev-bin
  libc6-dbg
  libc6-dev
  libc6-i386
  libc6
  libcaca-dev
  libcaca0
  libcaf-openmpi-3
  libcairo-gobject-perl
  libcairo-gobject2
  libcairo-perl
  libcairo-script-interpreter2
  libcairo2-dev
  libcairo2
  libcairomm-1.0-1v5
  libcamd2
  libcamel-1.2-62
  libcanberra-gtk3-0
  libcanberra-gtk3-module
  libcanberra-pulse
  libcanberra0
  libcap-ng0
  libcap2-bin
  libcap2
  libcbor0.6
  libcc1-0
  libccd-dev
  libccd2
  libccolamd2
  libcdio-cdda2
  libcdio-paranoia2
  libcdio18
  libcdparanoia0
  libcdr-0.1-1
  libcdt5
  libcfitsio-dev
  libcfitsio-doc
  libcfitsio8
  libcgraph6
  libcharls-dev
  libcharls2
  libcheese-gtk25
  libcheese8
  libcholmod3
  libchromaprint1
  libcilkrts5
  libclang-common-10-dev
  libclang-common-8-dev
  libclang-cpp10
  libclang1-10
  libclang1-8
  libclucene-contribs1v5
  libclucene-core1v5
  libclutter-1.0-0
  libclutter-1.0-common
  libclutter-gst-3.0-0
  libclutter-gtk-1.0-0
  libcmis-0.5-5v5
  libcoarrays-dev
  libcoarrays-openmpi-dev
  libcodec2-0.9
  libcogl-common
  libcogl-pango20
  libcogl-path20
  libcogl20
  libcolamd2
  libcolord-gtk1
  libcolord2
  libcolorhug2
  libcom-err2
  libconfig-file-perl
  libconsole-bridge-dev
  libconsole-bridge0.4
  libcrack2
  libcroco3
  libcrypt-dev
  libcrypt1
  libcryptsetup12
  libctf-nobfd0
  libctf0
  libcublas10
  libcublaslt10
  libcudart10.1
  libcue2
  libcufft10
  libcufftw10
  libcuinj64-10.1
  libcups2
  libcupsfilters1
  libcupsimage2
  libcupti-dev
  libcupti-doc
  libcupti10.1
  libcurand10
  libcurl3-gnutls
  libcurl4-openssl-dev
  libcurl4
  libcusolver10
  libcusolvermg10
  libcusparse10
  libdaemon0
  libdap-dev
  libdap25
  libdapclient6v5
  libdapserver7v5
  libdart-collision-bullet-dev
  libdart-collision-ode-dev
  libdart-dev
  libdart-external-ikfast-dev
  libdart-external-odelcpsolver-dev
  libdart-utils-dev
  libdart-utils-urdf-dev
  libdart6-collision-bullet
  libdart6-collision-ode
  libdart6-external-odelcpsolver
  libdart6-utils-urdf
  libdart6-utils
  libdart6
  libdata-dump-perl
  libdatrie-dev
  libdatrie1
  libdazzle-1.0-0
  libdb5.3
  libdbus-1-3
  libdbus-glib-1-2
  libdbusmenu-glib4
  libdbusmenu-gtk3-4
  libdc1394-22-dev
  libdc1394-22
  libdconf1
  libde265-0
  libdebconfclient0
  libdebhelper-perl
  libdee-1.0-4
  libdevmapper-event1.02.1
  libdevmapper1.02.1
  libdjvulibre-text
  libdjvulibre21
  libdmapsharing-3.0-2
  libdns-export1109
  libdotconf0
  libdouble-conversion3
  libdpkg-perl
  libdrm-amdgpu1
  libdrm-common
  libdrm-intel1
  libdrm-nouveau2
  libdrm-radeon1
  libdrm2
  libdv4
  libdw1
  libe-book-0.1-1
  libeatmydata1
  libebackend-1.2-10
  libebook-1.2-20
  libebook-contacts-1.2-3
  libecal-2.0-1
  libedata-book-1.2-26
  libedata-cal-2.0-1
  libedataserver-1.2-24
  libedataserverui-1.2-2
  libedit2
  libefiboot1
  libefivar1
  libegl-dev
  libegl-mesa0
  libegl1
  libeigen3-dev
  libelf1
  libenchant-2-2
  libencode-locale-perl
  libeot0
  libepoxy0
  libepsilon-dev
  libepsilon1
  libepubgen-0.1-1
  liberror-perl
  libespeak-ng1
  libestr0
  libetonyek-0.1-1
  libevdev2
  libevdocument3-4
  libevemu3
  libevent-2.1-7
  libevent-core-2.1-7
  libevent-dev
  libevent-extra-2.1-7
  libevent-openssl-2.1-7
  libevent-pthreads-2.1-7
  libevview3-3
  libexempi8
  libexif-dev
  libexif-doc
  libexif12
  libexiv2-27
  libexo-2-0
  libexo-common
  libexo-helpers
  libexpat1-dev
  libexpat1
  libext2fs2
  libexttextcat-2.0-0
  libexttextcat-data
  libextutils-depends-perl
  libextutils-pkgconfig-perl
  libfabric1
  libfakeroot
  libfastjson4
  libfcitx-config4
  libfcitx-gclient1
  libfcitx-utils0
  libfcl-dev
  libfcl0.5
  libfdisk1
  libffi-dev
  libffi7
  libfftw3-double3
  libfftw3-single3
  libfido2-1
  libfile-basedir-perl
  libfile-desktopentry-perl
  libfile-fcntllock-perl
  libfile-listing-perl
  libfile-mimeinfo-perl
  libfile-stripnondeterminism-perl
  libfl2
  libflac8
  libflann-dev
  libflann1.9
  libflite1
  libfltk-cairo1.3
  libfltk-forms1.3
  libfltk-gl1.3
  libfltk-images1.3
  libfltk1.3-dev
  libfltk1.3
  libfont-afm-perl
  libfontconfig1-dev
  libfontconfig1
  libfontembed1
  libfontenc1
  libfprint-2-2
  libfreehand-0.1-1
  libfreeimage-dev
  libfreeimage3
  libfreerdp-client2-2
  libfreerdp2-2
  libfreetype-dev
  libfreetype6-dev
  libfreetype6
  libfreexl-dev
  libfreexl1
  libfribidi-dev
  libfribidi0
  libfuse2
  libfuse3-3
  libfwupd2
  libfwupdplugin1
  libfwupdplugin5
  libfyba-dev
  libfyba0
  libgail-common
  libgail18
  libgamemode0
  libgamemodeauto0
  libgarcon-1-0
  libgarcon-common
  libgarcon-gtk3-1-0
  libgazebo11-dev
  libgazebo11
  libgbm1
  libgc1c2
  libgcab-1.0-0
  libgcc-7-dev
  libgcc-8-dev
  libgcc-9-dev
  libgcc-s1
  libgck-1-0
  libgcr-base-3-1
  libgcr-ui-3-1
  libgcrypt20
  libgd3
  libgdal-dev
  libgdal26
  libgdata-common
  libgdata22
  libgdbm-compat4
  libgdbm6
  libgdcm-dev
  libgdcm3.0
  libgdk-pixbuf2.0-0
  libgdk-pixbuf2.0-bin
  libgdk-pixbuf2.0-common
  libgdk-pixbuf2.0-dev
  libgdm1
  libgee-0.8-2
  libgegl-0.4-0
  libgegl-common
  libgeoclue-2-0
  libgeocode-glib0
  libgeos-3.8.0
  libgeos-c1v5
  libgeos-dev
  libgeotiff-dev
  libgeotiff5
  libgexiv2-2
  libgflags-dev
  libgflags2.2
  libgfortran-8-dev
  libgfortran-9-dev
  libgfortran5
  libgif-dev
  libgif7
  libgimp2.0
  libgirepository-1.0-1
  libgjs0g
  libgl-dev
  libgl1-mesa-dev
  libgl1-mesa-dri
  libgl1
  libgl2ps-dev
  libgl2ps1.4
  libglapi-mesa
  libgles-dev
  libgles1
  libgles2
  libglew-dev
  libglew2.1
  libglib-object-introspection-perl
  libglib-perl
  libglib2.0-0
  libglib2.0-bin
  libglib2.0-data
  libglib2.0-dev-bin
  libglib2.0-dev
  libglibmm-2.4-1v5
  libglu1-mesa-dev
  libglu1-mesa
  libglvnd-dev
  libglvnd0
  libglx-dev
  libglx-mesa0
  libglx0
  libgme0
  libgmp10
  libgnome-autoar-0-0
  libgnome-bluetooth13
  libgnome-desktop-3-19
  libgnome-games-support-1-3
  libgnome-games-support-common
  libgnome-menu-3-0
  libgnome-panel0
  libgnome-todo
  libgnomekbd-common
  libgnomekbd8
  libgnutls30
  libgoa-1.0-0b
  libgoa-1.0-common
  libgoa-backend-1.0-1
  libgom-1.0-0
  libgomp1
  libgoogle-glog-dev
  libgoogle-glog0v5
  libgpg-error-dev
  libgpg-error0
  libgpgme-dev
  libgpgme11
  libgpgmepp6
  libgphoto2-6
  libgphoto2-dev
  libgphoto2-l10n
  libgphoto2-port12
  libgpm2
  libgpod-common
  libgpod4
  libgraphene-1.0-0
  libgraphite2-3
  libgraphite2-dev
  libgrilo-0.3-0
  libgs9-common
  libgs9
  libgsf-1-114
  libgsf-1-common
  libgsm1
  libgsound0
  libgspell-1-2
  libgspell-1-common
  libgssapi-krb5-2
  libgssapi3-heimdal
  libgssdp-1.2-0
  libgssrpc4
  libgstreamer-gl1.0-0
  libgstreamer-plugins-base1.0-0
  libgstreamer-plugins-good1.0-0
  libgstreamer1.0-0
  libgtest-dev
  libgtk-3-0
  libgtk-3-bin
  libgtk-3-common
  libgtk2.0-0
  libgtk2.0-bin
  libgtk2.0-common
  libgtk2.0-dev
  libgtk3-perl
  libgtkmm-3.0-1v5
  libgtksourceview-4-0
  libgtksourceview-4-common
  libgtop-2.0-11
  libgtop2-common
  libgts-0.7-5
  libgts-bin
  libgts-dev
  libgudev-1.0-0
  libgupnp-1.2-0
  libgupnp-av-1.0-2
  libgupnp-dlna-2.0-3
  libgusb2
  libgvc6
  libgvpr2
  libgweather-3-16
  libgweather-common
  libgxps2
  libhandy-0.0-0
  libharfbuzz-dev
  libharfbuzz-gobject0
  libharfbuzz-icu0
  libharfbuzz0b
  libhcrypto4-heimdal
  libhdf4-0-alt
  libhdf4-alt-dev
  libhdf5-103
  libhdf5-cpp-103
  libhdf5-dev
  libhdf5-mpi-dev
  libhdf5-openmpi-103
  libhdf5-openmpi-dev
  libheif1
  libheimbase1-heimdal
  libheimntlm0-heimdal
  libhogweed5
  libhpmud0
  libhtml-form-perl
  libhtml-format-perl
  libhtml-parser-perl
  libhtml-tagset-perl
  libhtml-tree-perl
  libhttp-cookies-perl
  libhttp-daemon-perl
  libhttp-date-perl
  libhttp-message-perl
  libhttp-negotiate-perl
  libhunspell-1.7-0
  libhwloc-dev
  libhwloc-plugins
  libhwloc15
  libhx509-5-heimdal
  libhyphen0
  libibus-1.0-5
  libibverbs-dev
  libibverbs1
  libical3
  libice-dev
  libice6
  libicu-dev
  libicu66
  libidn11
  libidn2-0
  libido3-0.1-0
  libiec61883-0
  libieee1284-3
  libigdgmm11
  libignition-cmake2-dev
  libignition-common3-av-dev
  libignition-common3-av
  libignition-common3-core-dev
  libignition-common3-dev
  libignition-common3-events-dev
  libignition-common3-events
  libignition-common3-graphics-dev
  libignition-common3-graphics
  libignition-common3-profiler-dev
  libignition-common3-profiler
  libignition-common3
  libignition-fuel-tools4-dev
  libignition-fuel-tools4
  libignition-math6-dev
  libignition-math6
  libignition-msgs5-dev
  libignition-msgs5
  libignition-tools-dev
  libignition-transport8-core-dev
  libignition-transport8-dev
  libignition-transport8-log-dev
  libignition-transport8-log
  libignition-transport8
  libijs-0.35
  libilmbase-dev
  libilmbase24
  libimagequant0
  libimobiledevice6
  libindicator3-7
  libinput-bin
  libinput10
  libio-html-perl
  libio-socket-ssl-perl
  libio-stringy-perl
  libip4tc2
  libip6tc2
  libipc-system-simple-perl
  libisc-export1105
  libisl22
  libisns0
  libitm1
  libiw30
  libjack-jackd2-0
  libjansson4
  libjavascriptcoregtk-4.0-18
  libjbig-dev
  libjbig0
  libjbig2dec0
  libjcat1
  libjpeg-dev
  libjpeg-turbo8-dev
  libjpeg-turbo8
  libjpeg8-dev
  libjpeg8
  libjs-jquery-ui
  libjs-jquery
  libjson-c-dev
  libjson-c4
  libjson-glib-1.0-0
  libjson-glib-1.0-common
  libjsoncpp-dev
  libjsoncpp1
  libjuh-java
  libjurt-java
  libjxr0
  libk5crypto3
  libkadm5clnt-mit11
  libkadm5srv-mit11
  libkdb5-9
  libkeybinder-3.0-0
  libkeyutils1
  libklibc
  libkml-dev
  libkmlbase1
  libkmlconvenience1
  libkmldom1
  libkmlengine1
  libkmlregionator1
  libkmlxsd1
  libkmod2
  libkpathsea6
  libkrb5-26-heimdal
  libkrb5-3
  libkrb5-dev
  libkrb5support0
  libksba8
  liblab-gamut1
  liblangtag-common
  liblangtag1
  liblapack-dev
  liblapack3
  liblcms2-2
  liblcms2-utils
  libldap-2.4-2
  libldap-common
  libldap2-dev
  libldb2
  liblept5
  liblightdm-gobject-1-0
  liblilv-0-0
  liblirc-client0
  libllvm10
  libllvm12
  libllvm8
  liblmdb0
  liblocale-gettext-perl
  liblog4cxx-dev
  liblog4cxx10v5
  liblouis-data
  liblouis20
  liblouisutdml-bin
  liblouisutdml-data
  liblouisutdml9
  liblsan0
  libltdl-dev
  libltdl7
  liblua5.3-0
  liblvm2cmd2.03
  liblwp-mediatypes-perl
  liblwp-protocol-https-perl
  liblz4-1
  liblz4-dev
  liblzma-dev
  liblzma5
  liblzo2-2
  libmagic-mgc
  libmagic1
  libmail-sendmail-perl
  libmailtools-perl
  libmaxminddb0
  libmbim-glib4
  libmbim-proxy
  libmediaart-2.0-0
  libmessaging-menu0
  libmetis5
  libmhash2
  libminiupnpc17
  libminizip-dev
  libminizip1
  libmm-glib0
  libmng2
  libmnl0
  libmount-dev
  libmount1
  libmozjs-68-0
  libmp3lame0
  libmpc3
  libmpdec2
  libmpfr6
  libmpg123-0
  libmpx2
  libmspack0
  libmspub-0.1-1
  libmtdev1
  libmtp-common
  libmtp-runtime
  libmtp9
  libmutter-6-0
  libmwaw-0.3-3
  libmypaint-1.5-1
  libmypaint-common
  libmysofa1
  libmysqlclient-dev
  libmysqlclient21
  libmythes-1.2-0
  libnatpmp1
  libnautilus-extension1a
  libncurses-dev
  libncurses5
  libncurses6
  libncursesw6
  libndp0
  libneon27-gnutls
  libnet-dbus-perl
  libnet-http-perl
  libnet-smtp-ssl-perl
  libnet-ssleay-perl
  libnetcdf-c++4
  libnetcdf-cxx-legacy-dev
  libnetcdf-dev
  libnetcdf15
  libnetfilter-conntrack3
  libnetplan0
  libnettle7
  libnewt0.52
  libnfnetlink0
  libnfs13
  libnftnl11
  libnghttp2-14
  libnl-3-200
  libnl-3-dev
  libnl-genl-3-200
  libnl-route-3-200
  libnl-route-3-dev
  libnm0
  libnma0
  libnorm-dev
  libnorm1
  libnotify-bin
  libnotify4
  libnppc10
  libnppial10
  libnppicc10
  libnppicom10
  libnppidei10
  libnppif10
  libnppig10
  libnppim10
  libnppist10
  libnppisu10
  libnppitc10
  libnpps10
  libnpth0
  libnspr4
  libnss-mdns
  libnss-systemd
  libnss3
  libntfs-3g883
  libnuma-dev
  libnuma1
  libnvblas10
  libnvgraph10
  libnvidia-cfg1-535
  libnvidia-common-535
  libnvidia-compute-418
  libnvidia-compute-430
  libnvidia-compute-535
  libnvidia-decode-535
  libnvidia-encode-535
  libnvidia-extra-535
  libnvidia-fbc1-535
  libnvidia-gl-535
  libnvidia-ml-dev
  libnvjpeg10
  libnvrtc10.1
  libnvtoolsext1
  libnvvm3
  libobjc-8-dev
  libobjc-9-dev
  libobjc4
  liboctomap-dev
  liboctomap1.9
  libodbc1
  libode-dev
  libode8
  libodfgen-0.1-1
  libogdi-dev
  libogdi4.1
  libogg-dev
  libogg0
  libogre-1.9-dev
  libogre-1.9.0v5
  libomp-8-dev
  libomp5-8
  libopenal-data
  libopenal1
  libopencv-calib3d-dev
  libopencv-calib3d4.2
  libopencv-contrib-dev
  libopencv-contrib4.2
  libopencv-core-dev
  libopencv-core4.2
  libopencv-dev
  libopencv-dnn-dev
  libopencv-dnn4.2
  libopencv-features2d-dev
  libopencv-features2d4.2
  libopencv-flann-dev
  libopencv-flann4.2
  libopencv-highgui-dev
  libopencv-highgui4.2
  libopencv-imgcodecs-dev
  libopencv-imgcodecs4.2
  libopencv-imgproc-dev
  libopencv-imgproc4.2
  libopencv-ml-dev
  libopencv-ml4.2
  libopencv-objdetect-dev
  libopencv-objdetect4.2
  libopencv-photo-dev
  libopencv-photo4.2
  libopencv-shape-dev
  libopencv-shape4.2
  libopencv-stitching-dev
  libopencv-stitching4.2
  libopencv-superres-dev
  libopencv-superres4.2
  libopencv-ts-dev
  libopencv-video-dev
  libopencv-video4.2
  libopencv-videoio-dev
  libopencv-videoio4.2
  libopencv-videostab-dev
  libopencv-videostab4.2
  libopencv-viz-dev
  libopencv-viz4.2
  libopencv4.2-java
  libopencv4.2-jni
  libopenexr-dev
  libopenexr24
  libopengl-dev
  libopengl0
  libopenjp2-7-dev
  libopenjp2-7
  libopenmpi-dev
  libopenmpi3
  libopenmpt0
  libopenni-dev
  libopenni-sensor-pointclouds0
  libopenni0
  libopenni2-0
  libopenni2-dev
  libopus0
  liborc-0.4-0
  liborcus-0.15-0
  liborocos-bfl-dev
  liborocos-bfl0.8
  liborocos-kdl-dev
  liborocos-kdl1.4
  libp11-kit0
  libpackagekit-glib2-18
  libpagemaker-0.0-0
  libpam-cap
  libpam-fprintd
  libpam-gnome-keyring
  libpam-modules-bin
  libpam-modules
  libpam-runtime
  libpam-systemd
  libpam0g
  libpango-1.0-0
  libpango1.0-dev
  libpangocairo-1.0-0
  libpangoft2-1.0-0
  libpangomm-1.4-1v5
  libpangoxft-1.0-0
  libpaper-utils
  libpaper1
  libparted-fs-resize0
  libparted2
  libpathplan4
  libpcap0.8
  libpcaudio0
  libpci3
  libpciaccess0
  libpcl-apps1.10
  libpcl-common1.10
  libpcl-dev
  libpcl-features1.10
  libpcl-filters1.10
  libpcl-io1.10
  libpcl-kdtree1.10
  libpcl-keypoints1.10
  libpcl-ml1.10
  libpcl-octree1.10
  libpcl-outofcore1.10
  libpcl-people1.10
  libpcl-recognition1.10
  libpcl-registration1.10
  libpcl-sample-consensus1.10
  libpcl-search1.10
  libpcl-segmentation1.10
  libpcl-stereo1.10
  libpcl-surface1.10
  libpcl-tracking1.10
  libpcl-visualization1.10
  libpcre16-3
  libpcre2-16-0
  libpcre2-32-0
  libpcre2-8-0
  libpcre2-dev
  libpcre2-posix2
  libpcre3-dev
  libpcre32-3
  libpcre3
  libpcrecpp0v5
  libpcsclite1
  libpeas-1.0-0
  libpeas-common
  libperl5.30
  libpfm4
  libpgm-5.2-0
  libpgm-dev
  libphonenumber7
  libpipeline1
  libpixman-1-0
  libpixman-1-dev
  libpkcs11-helper1
  libplist3
  libplymouth5
  libpmix2
  libpng-dev
  libpng-tools
  libpng16-16
  libpoco-dev
  libpococrypto62
  libpocodata62
  libpocodatamysql62
  libpocodataodbc62
  libpocodatasqlite62
  libpocoencodings62
  libpocofoundation62
  libpocojson62
  libpocomongodb62
  libpoconet62
  libpoconetssl62
  libpocoredis62
  libpocoutil62
  libpocoxml62
  libpocozip62
  libpolkit-agent-1-0
  libpolkit-gobject-1-0
  libpoppler-cpp0v5
  libpoppler-dev
  libpoppler-glib8
  libpoppler-private-dev
  libpoppler97
  libpopt0
  libpostproc-dev
  libpostproc55
  libpq-dev
  libpq5
  libprocps8
  libproj-dev
  libproj15
  libprotobuf-dev
  libprotobuf-lite17
  libprotobuf17
  libprotoc-dev
  libprotoc17
  libproxy1-plugin-gsettings
  libproxy1-plugin-networkmanager
  libproxy1v5
  libpsl5
  libpsm-infinipath1
  libpsm2-2
  libpthread-stubs0-dev
  libpulse-dev
  libpulse-mainloop-glib0
  libpulse0
  libpulsedsp
  libpwquality-common
  libpwquality1
  libpyside2-dev
  libpyside2-py3-5.14
  libpython2-dev
  libpython2-stdlib
  libpython2.7-dev
  libpython2.7-minimal
  libpython2.7-stdlib
  libpython2.7
  libpython3-dev
  libpython3-stdlib
  libpython3.8-dev
  libpython3.8-minimal
  libpython3.8-stdlib
  libpython3.8
  libqhull-dev
  libqhull-r7
  libqhull7
  libqmi-glib5
  libqmi-proxy
  libqpdf26
  libqqwing2v5
  libqt5concurrent5
  libqt5core5a
  libqt5dbus5
  libqt5designer5
  libqt5designercomponents5
  libqt5gui5
  libqt5help5
  libqt5network5
  libqt5opengl5-dev
  libqt5opengl5
  libqt5positioning5
  libqt5printsupport5
  libqt5qml5
  libqt5quick5
  libqt5quickparticles5
  libqt5quickshapes5
  libqt5quicktest5
  libqt5quickwidgets5
  libqt5sensors5
  libqt5sql5-sqlite
  libqt5sql5
  libqt5svg5
  libqt5test5
  libqt5webchannel5
  libqt5webkit5-dev
  libqt5webkit5
  libqt5widgets5
  libqt5x11extras5
  libqt5xml5
  libquadmath0
  libqwt-qt5-6
  libqwt-qt5-dev
  libraptor2-0
  librasqal3
  libraw1394-11
  libraw1394-dev
  libraw1394-tools
  libraw19
  librdf0
  librdmacm1
  libreadline5
  libreadline8
  libreoffice-base-core
  libreoffice-calc
  libreoffice-common
  libreoffice-core
  libreoffice-draw
  libreoffice-gnome
  libreoffice-gtk3
  libreoffice-impress
  libreoffice-math
  libreoffice-pdfimport
  libreoffice-style-breeze
  libreoffice-style-colibre
  libreoffice-style-elementary
  libreoffice-style-tango
  libreoffice-writer
  librest-0.7-0
  librevenge-0.0-0
  librhash0
  librhythmbox-core10
  libridl-java
  libroken18-heimdal
  librsvg2-2
  librsvg2-common
  librsync2
  librtmp1
  librubberband2
  libruby2.7
  librygel-core-2.6-2
  librygel-db-2.6-2
  librygel-renderer-2.6-2
  librygel-server-2.6-2
  libsamplerate0
  libsane-common
  libsane-hpaio
  libsane
  libsasl2-2
  libsasl2-modules-db
  libsasl2-modules
  libsbc1
  libsctp-dev
  libsctp1
  libsdformat9-dev
  libsdformat9
  libsdl-image1.2-dev
  libsdl-image1.2
  libsdl1.2-dev
  libsdl1.2debian
  libsdl2-2.0-0
  libseccomp2
  libsecret-1-0
  libsecret-common
  libselinux1-dev
  libselinux1
  libsemanage-common
  libsemanage1
  libsensors-config
  libsensors5
  libsepol1-dev
  libsepol1
  libserd-0-0
  libserf-1-1
  libsgutils2-2
  libshiboken2-dev
  libshiboken2-py3-5.14
  libshine3
  libshout3
  libsigc++-2.0-0v5
  libsigsegv2
  libsimbody-dev
  libsimbody3.6
  libslang2-dev
  libslang2
  libsm-dev
  libsm6
  libsmartcols1
  libsmbclient
  libsmbios-c2
  libsnapd-glib1
  libsnappy1v5
  libsndfile1
  libsndio7.0
  libsnmp-base
  libsnmp35
  libsocket++1
  libsodium-dev
  libsodium23
  libsonic0
  libsord-0-0
  libsoup-gnome2.4-1
  libsoup2.4-1
  libsoxr0
  libspatialite-dev
  libspatialite7
  libspectre1
  libspeechd2
  libspeex1
  libspeexdsp1
  libspnav0
  libsqlite3-0
  libsqlite3-dev
  libsratom-0-0
  libss2
  libssh-4
  libssh-gcrypt-4
  libssl-dev
  libssl1.1
  libstartup-notification0
  libstdc++-7-dev
  libstdc++-8-dev
  libstdc++-9-dev
  libstdc++6
  libstemmer0d
  libsub-override-perl
  libsuitesparseconfig5
  libsuperlu-dev
  libsuperlu5
  libsvn1
  libswresample-dev
  libswresample3
  libswscale-dev
  libswscale5
  libsynctex2
  libsys-hostname-long-perl
  libsysmetrics1
  libsystemd0
  libsz2
  libtag1v5-vanilla
  libtag1v5
  libtalloc2
  libtar-dev
  libtar0
  libtasn1-6
  libtbb-dev
  libtbb2
  libtcl8.6
  libtdb1
  libteamdctl0
  libtepl-4-0
  libtesseract4
  libtevent0
  libtext-charwidth-perl
  libtext-iconv-perl
  libtext-wrapi18n-perl
  libthai-data
  libthai-dev
  libthai0
  libtheora-dev
  libtheora0
  libthrust-dev
  libthunarx-3-0
  libtie-ixhash-perl
  libtiff-dev
  libtiff5-dev
  libtiff5
  libtiffxx5
  libtimedate-perl
  libtinfo-dev
  libtinfo5
  libtinfo6
  libtinyxml-dev
  libtinyxml2-6a
  libtinyxml2-dev
  libtinyxml2.6.2v5
  libtk8.6
  libtool
  libtotem-plparser-common
  libtotem-plparser18
  libtotem0
  libtracker-control-2.0-0
  libtracker-miner-2.0-0
  libtracker-sparql-2.0-0
  libtry-tiny-perl
  libtsan0
  libtss2-esys0
  libtumbler-1-0
  libtwolame0
  libu2f-udev
  libubsan0
  libubsan1
  libuchardet0
  libudev1
  libudisks2-0
  libumfpack5
  libunistring2
  libunity-gtk2-parser0
  libunity-gtk3-parser0
  libunity-protocol-private0
  libunity-scopes-json-def-desktop
  libunity-settings-daemon1
  libunity9
  libuno-cppu3
  libuno-cppuhelpergcc3-3
  libuno-purpenvhelpergcc3-3
  libuno-sal3
  libuno-salhelpergcc3-3
  libunoloader-java
  libunwind8
  libupower-glib3
  liburcu6
  liburdfdom-dev
  liburdfdom-headers-dev
  liburdfdom-model-state
  liburdfdom-model
  liburdfdom-sensor
  liburdfdom-world
  liburi-perl
  liburiparser-dev
  liburiparser1
  liburl-dispatcher1
  libusb-1.0-0-dev
  libusb-1.0-0
  libusb-1.0-doc
  libusbmuxd6
  libutempter0
  libutf8proc2
  libuuid1
  libuv1
  libv4l-0
  libv4lconvert0
  libva-drm2
  libva-x11-2
  libva2
  libvdpau-dev
  libvdpau1
  libvidstab1.1
  libvisio-0.1-1
  libvisual-0.4-0
  libvncclient1
  libvolume-key1
  libvorbis0a
  libvorbisenc2
  libvorbisfile3
  libvpx6
  libvte-2.91-0
  libvte-2.91-common
  libvtk6.3
  libvtk7-dev
  libvtk7-java
  libvtk7-jni
  libvtk7-qt-dev
  libvtk7.1p-qt
  libvtk7.1p
  libvulkan-dev
  libvulkan1
  libwacom-bin
  libwacom-common
  libwacom2
  libwavpack1
  libwayland-client0
  libwayland-cursor0
  libwayland-egl1
  libwayland-server0
  libwbclient0
  libwebkit2gtk-4.0-37
  libwebp-dev
  libwebp6
  libwebpdemux2
  libwebpmux3
  libwebrtc-audio-processing1
  libwhoopsie-preferences0
  libwhoopsie0
  libwind0-heimdal
  libwinpr2-2
  libwmf0.2-7-gtk
  libwmf0.2-7
  libwnck-3-0
  libwnck-3-common
  libwoff1
  libwpd-0.10-10
  libwpg-0.3-3
  libwps-0.4-4
  libwrap0
  libwww-perl
  libwww-robotrules-perl
  libx11-6
  libx11-data
  libx11-dev
  libx11-protocol-perl
  libx11-xcb1
  libx264-155
  libx265-179
  libxatracker2
  libxau-dev
  libxau6
  libxaw7
  libxcb-damage0
  libxcb-dri2-0
  libxcb-dri3-0
  libxcb-glx0
  libxcb-icccm4
  libxcb-image0
  libxcb-keysyms1
  libxcb-present0
  libxcb-randr0
  libxcb-render-util0
  libxcb-render0-dev
  libxcb-render0
  libxcb-res0
  libxcb-shape0
  libxcb-shm0-dev
  libxcb-shm0
  libxcb-sync1
  libxcb-util1
  libxcb-xfixes0
  libxcb-xinerama0
  libxcb-xinput0
  libxcb-xkb1
  libxcb-xtest0
  libxcb-xv0
  libxcb1-dev
  libxcb1
  libxcomposite-dev
  libxcomposite1
  libxcursor-dev
  libxcursor1
  libxdamage-dev
  libxdamage1
  libxdmcp-dev
  libxdmcp6
  libxerces-c-dev
  libxerces-c3.2
  libxext-dev
  libxext6
  libxfce4panel-2.0-4
  libxfce4ui-1-0
  libxfce4ui-2-0
  libxfce4ui-common
  libxfce4ui-utils
  libxfce4util-bin
  libxfce4util-common
  libxfce4util7
  libxfconf-0-3
  libxfixes-dev
  libxfixes3
  libxfont2
  libxft-dev
  libxft2
  libxi-dev
  libxi6
  libxinerama-dev
  libxinerama1
  libxkbcommon-x11-0
  libxkbcommon0
  libxkbfile1
  libxklavier16
  libxml-parser-perl
  libxml-twig-perl
  libxml-xpathengine-perl
  libxml2-dev
  libxml2-utils
  libxml2
  libxmlb1
  libxmlb2
  libxmlsec1-nss
  libxmlsec1-openssl
  libxmlsec1
  libxmu-dev
  libxmu-headers
  libxmu6
  libxmuu1
  libxnvctrl0
  libxpm4
  libxpresent1
  libxrandr-dev
  libxrandr2
  libxrender-dev
  libxrender1
  libxres1
  libxshmfence1
  libxslt1.1
  libxss-dev
  libxss1
  libxt-dev
  libxt6
  libxtables12
  libxtst6
  libxv1
  libxvidcore4
  libxvmc1
  libxxf86dga1
  libxxf86vm1
  libyajl2
  libyaml-0-2
  libyaml-cpp-dev
  libyaml-cpp0.6
  libyaml-dev
  libyelp0
  libz3-4
  libz3-dev
  libzip-dev
  libzip5
  libzmq3-dev
  libzmq5
  libzstd-dev
  libzstd1
  libzvbi-common
  libzvbi0
  libzzip-0-13
  lightdm
  linux-aws-5.15-headers-5.15.0-1036
  linux-aws-5.15-headers-5.15.0-1047
  linux-aws
  linux-base
  linux-headers-5.15.0-1036-aws
  linux-headers-5.15.0-1047-aws
  linux-headers-aws
  linux-image-5.15.0-1036-aws
  linux-image-5.15.0-1047-aws
  linux-image-aws
  linux-libc-dev
  linux-modules-5.15.0-1036-aws
  linux-modules-5.15.0-1047-aws
  linux-sound-base
  lld-10
  lld-8
  llvm-10-dev
  llvm-10-runtime
  llvm-10-tools
  llvm-10
  llvm-8-dev
  llvm-8-runtime
  llvm-8
  lm-sensors
  locales
  login
  logrotate
  logsave
  lp-solve
  lsb-base
  lsb-release
  lshw
  lsof
  ltrace
  lvm2
  lxd-agent-loader
  lz4
  m4
  make
  man-db
  manpages-dev
  manpages
  mawk
  mdadm
  media-player-info
  memtest86+
  mercurial-common
  mercurial
  mesa-utils
  mesa-va-drivers
  mesa-vdpau-drivers
  mesa-vulkan-drivers
  microcode-initrd
  mime-support
  mobile-broadband-provider-info
  modemmanager
  mokutil
  motd-news-config
  mount
  mousetweaks
  mpi-default-bin
  mpi-default-dev
  mscompress
  mtools
  mtr-tiny
  multipath-tools
  mutter-common
  mutter
  mysql-common
  nano
  nautilus-data
  nautilus-extension-gnome-terminal
  nautilus-sendto
  nautilus-share
  nautilus
  ncurses-base
  ncurses-bin
  ncurses-term
  netbase
  netcat-openbsd
  netplan.io
  network-manager-config-connectivity-ubuntu
  network-manager-gnome
  network-manager-openvpn-gnome
  network-manager-openvpn
  network-manager-pptp-gnome
  network-manager-pptp
  network-manager
  networkd-dispatcher
  nice-dcv-gl
  nice-dcv-server
  nice-dcv-simple-external-authenticator
  nice-dcv-web-viewer
  nice-xdcv
  ninja-build
  node-html5shiv
  ntfs-3g
  nvidia-compute-utils-535
  nvidia-cuda-dev
  nvidia-cuda-doc
  nvidia-cuda-gdb
  nvidia-cuda-toolkit
  nvidia-dkms-535
  nvidia-driver-535
  nvidia-kernel-common-535
  nvidia-kernel-source-535
  nvidia-modprobe
  nvidia-opencl-dev
  nvidia-prime
  nvidia-profiler
  nvidia-settings
  nvidia-utils-535
  nvidia-visual-profiler
  nvtop
  ocl-icd-libopencl1
  ocl-icd-opencl-dev
  odbcinst1debian2
  odbcinst
  open-iscsi
  open-vm-tools
  opencl-c-headers
  opencv-data
  openjdk-8-jre-headless
  openjdk-8-jre
  openmpi-bin
  openmpi-common
  openni-utils
  openprinting-ppds
  openssh-client
  openssh-server
  openssh-sftp-server
  openssl
  openvpn
  orca
  os-prober
  overlayroot
  p11-kit-modules
  p11-kit
  packagekit-tools
  packagekit
  pango1.0-tools
  parted
  passwd
  pastebinit
  patch
  pavucontrol
  pci.ids
  pciutils
  pcmciautils
  perl-base
  perl-modules-5.30
  perl-openssl-defaults
  perl
  pinentry-curses
  pinentry-gnome3
  pkg-config
  plymouth-label
  plymouth-theme-spinner
  plymouth-theme-ubuntu-text
  plymouth
  po-debconf
  policykit-1
  policykit-desktop-privileges
  pollinate
  poppler-data
  poppler-utils
  popularity-contest
  powermgmt-base
  ppp
  pptp-linux
  printer-driver-brlaser
  printer-driver-c2esp
  printer-driver-foo2zjs-common
  printer-driver-foo2zjs
  printer-driver-hpcups
  printer-driver-m2300w
  printer-driver-min12xxw
  printer-driver-pnm2ppa
  printer-driver-postscript-hp
  printer-driver-ptouch
  printer-driver-pxljr
  printer-driver-sag-gdi
  printer-driver-splix
  procps
  proj-bin
  proj-data
  protobuf-compiler
  psmisc
  publicsuffix
  pulseaudio-module-bluetooth
  pulseaudio-utils
  pulseaudio
  pyqt5-dev
  python-apt-common
  python-dev-is-python2
  python-is-python2
  python-matplotlib-data
  python-pip-whl
  python2-dev
  python2-minimal
  python2.7-dev
  python2.7-minimal
  python2.7
  python2
  python3-apport
  python3-apt
  python3-aptdaemon.gtk3widgets
  python3-aptdaemon
  python3-attr
  python3-autobahn
  python3-automat
  python3-bcrypt
  python3-blinker
  python3-breezy
  python3-brlapi
  python3-cairo
  python3-catkin-pkg-modules
  python3-catkin-pkg
  python3-cbor
  python3-certifi
  python3-cffi-backend
  python3-chardet
  python3-click
  python3-colorama
  python3-commandnotfound
  python3-configobj
  python3-constantly
  python3-cryptography
  python3-cups
  python3-cupshelpers
  python3-cycler
  python3-dateutil
  python3-dbus
  python3-debconf
  python3-debian
  python3-defer
  python3-defusedxml
  python3-deprecated
  python3-dev
  python3-distro-info
  python3-distro
  python3-distupgrade
  python3-distutils
  python3-docutils
  python3-dulwich
  python3-empy
  python3-entrypoints
  python3-fasteners
  python3-fastimport
  python3-future
  python3-gdbm
  python3-gi-cairo
  python3-gi
  python3-github
  python3-gitlab
  python3-gnupg
  python3-gpg
  python3-hamcrest
  python3-httplib2
  python3-hyperlink
  python3-ibus-1.0
  python3-idna
  python3-importlib-metadata
  python3-incremental
  python3-jinja2
  python3-json-pointer
  python3-jsonpatch
  python3-jsonschema
  python3-jwt
  python3-keyring
  python3-kiwisolver
  python3-launchpadlib
  python3-lazr.restfulclient
  python3-lazr.uri
  python3-ldb
  python3-lib2to3
  python3-lockfile
  python3-louis
  python3-lz4
  python3-macaroonbakery
  python3-mako
  python3-markupsafe
  python3-matplotlib
  python3-minimal
  python3-monotonic
  python3-more-itertools
  python3-mpi4py
  python3-nacl
  python3-netifaces
  python3-newt
  python3-nose
  python3-numpy
  python3-oauthlib
  python3-olefile
  python3-opencv
  python3-opengl
  python3-openssl
  python3-paramiko
  python3-pexpect
  python3-pil
  python3-pip
  python3-pkg-resources
  python3-png
  python3-problem-report
  python3-protobuf
  python3-psutil
  python3-ptyprocess
  python3-pyasn1-modules
  python3-pyasn1
  python3-pyatspi
  python3-pycryptodome
  python3-pydot
  python3-pygments
  python3-pykdl
  python3-pymacaroons
  python3-pyparsing
  python3-pyqrcode
  python3-pyqt5.qtopengl
  python3-pyqt5.qtsvg
  python3-pyqt5.qtwebkit
  python3-pyqt5
  python3-pyrsistent
  python3-pyside2.qtcore
  python3-pyside2.qtgui
  python3-pyside2.qtsvg
  python3-pyside2.qtwidgets
  python3-renderpm
  python3-reportlab-accel
  python3-reportlab
  python3-requests-unixsocket
  python3-requests
  python3-rfc3339
  python3-roman
  python3-rosdep-modules
  python3-rosdep
  python3-rosdistro-modules
  python3-rosdistro
  python3-rosinstall-generator
  python3-rosinstall
  python3-rospkg-modules
  python3-rospkg
  python3-secretstorage
  python3-serial
  python3-service-identity
  python3-setuptools
  python3-simplejson
  python3-sip-dev
  python3-sip
  python3-six
  python3-snappy
  python3-software-properties
  python3-speechd
  python3-systemd
  python3-talloc
  python3-tk
  python3-trie
  python3-twisted-bin
  python3-twisted
  python3-txaio
  python3-tz
  python3-u-msgpack
  python3-ubjson
  python3-uno
  python3-update-manager
  python3-urllib3
  python3-vcstools
  python3-vtk7
  python3-wadllib
  python3-wheel
  python3-wrapt
  python3-wsaccel
  python3-wstool
  python3-xdg
  python3-xkit
  python3-yaml
  python3-zipp
  python3-zope.interface
  python3.8-dev
  python3.8-minimal
  python3.8
  python3
  qdoc-qt5
  qhelpgenerator-qt5
  qt5-assistant
  qt5-gtk-platformtheme
  qt5-qmake-bin
  qt5-qmake
  qt5-qmltooling-plugins
  qtattributionsscanner-qt5
  qtbase5-dev-tools
  qtbase5-dev
  qtchooser
  qtdeclarative5-dev-tools
  qtdeclarative5-dev
  qttools5-dev-tools
  qttools5-dev
  qttools5-private-dev
  qttranslations5-l10n
  rake
  readline-common
  remmina-common
  remmina-plugin-rdp
  remmina-plugin-secret
  remmina-plugin-vnc
  remmina
  rfkill
  rhythmbox-data
  rhythmbox-plugin-alternative-toolbar
  rhythmbox-plugins
  rhythmbox
  ros-noetic-actionlib-msgs
  ros-noetic-actionlib-tutorials
  ros-noetic-actionlib
  ros-noetic-amcl
  ros-noetic-angles
  ros-noetic-base-local-planner
  ros-noetic-bond-core
  ros-noetic-bond
  ros-noetic-bondcpp
  ros-noetic-bondpy
  ros-noetic-camera-calibration-parsers
  ros-noetic-camera-calibration
  ros-noetic-camera-info-manager
  ros-noetic-capabilities
  ros-noetic-carrot-planner
  ros-noetic-catkin
  ros-noetic-class-loader
  ros-noetic-clear-costmap-recovery
  ros-noetic-cmake-modules
  ros-noetic-common-msgs
  ros-noetic-common-tutorials
  ros-noetic-compressed-depth-image-transport
  ros-noetic-compressed-image-transport
  ros-noetic-control-msgs
  ros-noetic-control-toolbox
  ros-noetic-controller-interface
  ros-noetic-controller-manager-msgs
  ros-noetic-controller-manager
  ros-noetic-costmap-2d
  ros-noetic-cpp-common
  ros-noetic-create-description
  ros-noetic-cv-bridge
  ros-noetic-depth-image-proc
  ros-noetic-depthimage-to-laserscan
  ros-noetic-desktop-full
  ros-noetic-desktop
  ros-noetic-diagnostic-aggregator
  ros-noetic-diagnostic-analysis
  ros-noetic-diagnostic-common-diagnostics
  ros-noetic-diagnostic-msgs
  ros-noetic-diagnostic-updater
  ros-noetic-diagnostics
  ros-noetic-diff-drive-controller
  ros-noetic-dwa-local-planner
  ros-noetic-dynamic-reconfigure
  ros-noetic-ecl-build
  ros-noetic-ecl-command-line
  ros-noetic-ecl-concepts
  ros-noetic-ecl-config
  ros-noetic-ecl-console
  ros-noetic-ecl-containers
  ros-noetic-ecl-converters
  ros-noetic-ecl-devices
  ros-noetic-ecl-eigen
  ros-noetic-ecl-errors
  ros-noetic-ecl-exceptions
  ros-noetic-ecl-formatters
  ros-noetic-ecl-geometry
  ros-noetic-ecl-license
  ros-noetic-ecl-linear-algebra
  ros-noetic-ecl-math
  ros-noetic-ecl-mobile-robot
  ros-noetic-ecl-mpl
  ros-noetic-ecl-sigslots
  ros-noetic-ecl-threads
  ros-noetic-ecl-time-lite
  ros-noetic-ecl-time
  ros-noetic-ecl-type-traits
  ros-noetic-ecl-utilities
  ros-noetic-eigen-conversions
  ros-noetic-executive-smach
  ros-noetic-fake-localization
  ros-noetic-filters
  ros-noetic-forward-command-controller
  ros-noetic-gazebo-dev
  ros-noetic-gazebo-msgs
  ros-noetic-gazebo-plugins
  ros-noetic-gazebo-ros-control
  ros-noetic-gazebo-ros-pkgs
  ros-noetic-gazebo-ros
  ros-noetic-gencpp
  ros-noetic-geneus
  ros-noetic-genlisp
  ros-noetic-genmsg
  ros-noetic-gennodejs
  ros-noetic-genpy
  ros-noetic-geometry-msgs
  ros-noetic-geometry-tutorials
  ros-noetic-geometry
  ros-noetic-gl-dependency
  ros-noetic-global-planner
  ros-noetic-hardware-interface
  ros-noetic-image-common
  ros-noetic-image-geometry
  ros-noetic-image-pipeline
  ros-noetic-image-proc
  ros-noetic-image-publisher
  ros-noetic-image-rotate
  ros-noetic-image-transport-plugins
  ros-noetic-image-transport
  ros-noetic-image-view
  ros-noetic-interactive-marker-tutorials
  ros-noetic-interactive-markers
  ros-noetic-joint-limits-interface
  ros-noetic-joint-state-controller
  ros-noetic-joint-state-publisher-gui
  ros-noetic-joint-state-publisher
  ros-noetic-joy
  ros-noetic-kdl-conversions
  ros-noetic-kdl-parser
  ros-noetic-kobuki-dock-drive
  ros-noetic-kobuki-driver
  ros-noetic-kobuki-msgs
  ros-noetic-laptop-battery-monitor
  ros-noetic-laser-assembler
  ros-noetic-laser-filters
  ros-noetic-laser-geometry
  ros-noetic-laser-pipeline
  ros-noetic-librviz-tutorial
  ros-noetic-map-msgs
  ros-noetic-map-server
  ros-noetic-media-export
  ros-noetic-message-filters
  ros-noetic-message-generation
  ros-noetic-message-runtime
  ros-noetic-mk
  ros-noetic-move-base-msgs
  ros-noetic-move-base
  ros-noetic-move-slow-and-clear
  ros-noetic-nav-core
  ros-noetic-nav-msgs
  ros-noetic-navfn
  ros-noetic-navigation
  ros-noetic-nodelet-core
  ros-noetic-nodelet-topic-tools
  ros-noetic-nodelet-tutorial-math
  ros-noetic-nodelet
  ros-noetic-openni-camera
  ros-noetic-openni-launch
  ros-noetic-openslam-gmapping
  ros-noetic-pcl-conversions
  ros-noetic-pcl-msgs
  ros-noetic-pcl-ros
  ros-noetic-perception-pcl
  ros-noetic-perception
  ros-noetic-pluginlib-tutorials
  ros-noetic-pluginlib
  ros-noetic-polled-camera
  ros-noetic-position-controllers
  ros-noetic-python-qt-binding
  ros-noetic-qt-dotgraph
  ros-noetic-qt-gui-cpp
  ros-noetic-qt-gui-py-common
  ros-noetic-qt-gui
  ros-noetic-qwt-dependency
  ros-noetic-realtime-tools
  ros-noetic-resource-retriever
  ros-noetic-rgbd-launch
  ros-noetic-robot-pose-ekf
  ros-noetic-robot-state-publisher
  ros-noetic-robot
  ros-noetic-ros-base
  ros-noetic-ros-comm
  ros-noetic-ros-core
  ros-noetic-ros-environment
  ros-noetic-ros-tutorials
  ros-noetic-ros
  ros-noetic-rosbag-migration-rule
  ros-noetic-rosbag-storage
  ros-noetic-rosbag
  ros-noetic-rosbash
  ros-noetic-rosboost-cfg
  ros-noetic-rosbuild
  ros-noetic-rosclean
  ros-noetic-rosconsole-bridge
  ros-noetic-rosconsole
  ros-noetic-roscpp-core
  ros-noetic-roscpp-serialization
  ros-noetic-roscpp-traits
  ros-noetic-roscpp-tutorials
  ros-noetic-roscpp
  ros-noetic-roscreate
  ros-noetic-rosgraph-msgs
  ros-noetic-rosgraph
  ros-noetic-roslang
  ros-noetic-roslaunch
  ros-noetic-roslib
  ros-noetic-roslint
  ros-noetic-roslisp
  ros-noetic-roslz4
  ros-noetic-rosmake
  ros-noetic-rosmaster
  ros-noetic-rosmsg
  ros-noetic-rosnode
  ros-noetic-rosout
  ros-noetic-rospack
  ros-noetic-rosparam
  ros-noetic-rospy-tutorials
  ros-noetic-rospy
  ros-noetic-rosservice
  ros-noetic-rostest
  ros-noetic-rostime
  ros-noetic-rostopic
  ros-noetic-rosunit
  ros-noetic-roswtf
  ros-noetic-rotate-recovery
  ros-noetic-rqt-action
  ros-noetic-rqt-bag-plugins
  ros-noetic-rqt-bag
  ros-noetic-rqt-common-plugins
  ros-noetic-rqt-console
  ros-noetic-rqt-dep
  ros-noetic-rqt-graph
  ros-noetic-rqt-gui-cpp
  ros-noetic-rqt-gui-py
  ros-noetic-rqt-gui
  ros-noetic-rqt-image-view
  ros-noetic-rqt-launch
  ros-noetic-rqt-logger-level
  ros-noetic-rqt-moveit
  ros-noetic-rqt-msg
  ros-noetic-rqt-nav-view
  ros-noetic-rqt-plot
  ros-noetic-rqt-pose-view
  ros-noetic-rqt-publisher
  ros-noetic-rqt-py-common
  ros-noetic-rqt-py-console
  ros-noetic-rqt-reconfigure
  ros-noetic-rqt-robot-dashboard
  ros-noetic-rqt-robot-monitor
  ros-noetic-rqt-robot-plugins
  ros-noetic-rqt-robot-steering
  ros-noetic-rqt-runtime-monitor
  ros-noetic-rqt-rviz
  ros-noetic-rqt-service-caller
  ros-noetic-rqt-shell
  ros-noetic-rqt-srv
  ros-noetic-rqt-tf-tree
  ros-noetic-rqt-top
  ros-noetic-rqt-topic
  ros-noetic-rqt-web
  ros-noetic-rviz-plugin-tutorials
  ros-noetic-rviz-python-tutorial
  ros-noetic-rviz
  ros-noetic-self-test
  ros-noetic-sensor-msgs
  ros-noetic-shape-msgs
  ros-noetic-simulators
  ros-noetic-smach-msgs
  ros-noetic-smach-ros
  ros-noetic-smach
  ros-noetic-smclib
  ros-noetic-sophus
  ros-noetic-stage-ros
  ros-noetic-stage
  ros-noetic-std-msgs
  ros-noetic-std-srvs
  ros-noetic-stereo-image-proc
  ros-noetic-stereo-msgs
  ros-noetic-tf-conversions
  ros-noetic-tf2-eigen
  ros-noetic-tf2-geometry-msgs
  ros-noetic-tf2-kdl
  ros-noetic-tf2-msgs
  ros-noetic-tf2-py
  ros-noetic-tf2-ros
  ros-noetic-tf2
  ros-noetic-tf
  ros-noetic-theora-image-transport
  ros-noetic-topic-tools
  ros-noetic-trajectory-msgs
  ros-noetic-transmission-interface
  ros-noetic-turtle-actionlib
  ros-noetic-turtle-tf2
  ros-noetic-turtle-tf
  ros-noetic-turtlesim
  ros-noetic-twist-mux-msgs
  ros-noetic-twist-mux
  ros-noetic-urdf-parser-plugin
  ros-noetic-urdf-sim-tutorial
  ros-noetic-urdf-tutorial
  ros-noetic-urdf
  ros-noetic-vision-opencv
  ros-noetic-visualization-marker-tutorials
  ros-noetic-visualization-msgs
  ros-noetic-visualization-tutorials
  ros-noetic-viz
  ros-noetic-voxel-grid
  ros-noetic-webkit-dependency
  ros-noetic-xacro
  ros-noetic-xmlrpcpp
  rsync
  rsyslog
  rtkit
  ruby-minitest
  ruby-net-telnet
  ruby-power-assert
  ruby-test-unit
  ruby-xmlrpc
  ruby2.7
  ruby
  rubygems-integration
  run-one
  rygel
  samba-libs
  sane-utils
  sbcl
  sbsigntool
  screen-resolution-extra
  screen
  sdformat9-sdf
  seahorse
  secureboot-db
  sed
  sensible-utils
  session-migration
  sg3-utils-udev
  sg3-utils
  sgml-base
  sgml-data
  shared-mime-info
  shiboken2
  shim-signed
  shotwell-common
  shotwell
  simple-scan
  sip-dev
  snapd
  software-properties-common
  software-properties-gtk
  sosreport
  sound-icons
  sound-theme-freedesktop
  speech-dispatcher-audio-plugins
  speech-dispatcher-espeak-ng
  speech-dispatcher
  spice-vdagent
  squashfs-tools
  ssh-import-id
  ssl-cert
  strace
  subversion
  sudo
  switcheroo-control
  syslinux-common
  syslinux-legacy
  syslinux
  system-config-printer-common
  system-config-printer-udev
  system-config-printer
  systemd-sysv
  systemd-timesyncd
  systemd
  sysvinit-utils
  tango-icon-theme
  tar
  tcl-dev
  tcl-vtk7
  tcl8.6-dev
  tcl8.6
  tcl
  tcpdump
  telnet
  thin-provisioning-tools
  thunar-data
  thunar-volman
  thunar
  thunderbird-gnome-support
  thunderbird
  time
  tk-dev
  tk8.6-blt2.5
  tk8.6-dev
  tk8.6
  tk
  tmux
  totem-common
  totem-plugins
  totem
  tpm-udev
  tracker-extract
  tracker-miner-fs
  tracker
  transmission-common
  transmission-gtk
  ttf-bitstream-vera
  ttf-dejavu-core
  tumbler-common
  tumbler
  tzdata
  ubuntu-advantage-desktop-daemon
  ubuntu-advantage-tools
  ubuntu-desktop-minimal
  ubuntu-desktop
  ubuntu-docs
  ubuntu-drivers-common
  ubuntu-keyring
  ubuntu-minimal
  ubuntu-mono
  ubuntu-release-upgrader-core
  ubuntu-release-upgrader-gtk
  ubuntu-report
  ubuntu-server
  ubuntu-session
  ubuntu-settings
  ubuntu-standard
  ubuntu-touch-sounds
  ubuntu-wallpapers-focal
  ubuntu-wallpapers
  ucf
  udev
  udisks2
  ufw
  unattended-upgrades
  unity-greeter
  unity-gtk-module-common
  unity-gtk2-module
  unity-gtk3-module
  unity-settings-daemon-schemas
  unity-settings-daemon
  unixodbc-dev
  uno-libs-private
  unzip
  update-inetd
  update-manager-core
  update-manager
  update-notifier-common
  update-notifier
  upower
  ure
  usb-creator-common
  usb-creator-gtk
  usb-modeswitch-data
  usb-modeswitch
  usb.ids
  usbmuxd
  usbutils
  util-linux
  uuid-dev
  uuid-runtime
  va-driver-all
  vdpau-driver-all
  vim-common
  vim-runtime
  vim-tiny
  vim
  vino
  vtk7
  wamerican
  wget
  whiptail
  whoopsie-preferences
  whoopsie
  wireless-regdb
  wireless-tools
  wpasupplicant
  x11-apps
  x11-common
  x11-session-utils
  x11-utils
  x11-xkb-utils
  x11-xserver-utils
  x11proto-core-dev
  x11proto-dev
  x11proto-input-dev
  x11proto-randr-dev
  x11proto-scrnsaver-dev
  x11proto-xext-dev
  x11proto-xinerama-dev
  xauth
  xbitmaps
  xbrlapi
  xcursor-themes
  xdg-dbus-proxy
  xdg-desktop-portal-gtk
  xdg-desktop-portal
  xdg-user-dirs-gtk
  xdg-user-dirs
  xdg-utils
  xfce4-appfinder
  xfce4-notifyd
  xfce4-panel
  xfce4-pulseaudio-plugin
  xfce4-session
  xfce4-settings
  xfce4
  xfconf
  xfdesktop4-data
  xfdesktop4
  xfonts-base
  xfonts-encodings
  xfonts-scalable
  xfonts-utils
  xfsprogs
  xfwm4
  xiccd
  xinit
  xinput
  xkb-data
  xml-core
  xorg-docs-core
  xorg-sgml-doctools
  xorg
  xorgxrdp
  xrdp
  xserver-common
  xserver-xephyr
  xserver-xorg-core
  xserver-xorg-input-all
  xserver-xorg-input-libinput
  xserver-xorg-input-wacom
  xserver-xorg-legacy
  xserver-xorg-video-all
  xserver-xorg-video-amdgpu
  xserver-xorg-video-ati
  xserver-xorg-video-fbdev
  xserver-xorg-video-intel
  xserver-xorg-video-nouveau
  xserver-xorg-video-nvidia-535
  xserver-xorg-video-qxl
  xserver-xorg-video-radeon
  xserver-xorg-video-vesa
  xserver-xorg-video-vmware
  xserver-xorg
  xterm
  xtrans-dev
  xul-ext-ubufox
  xwayland
  xxd
  xz-utils
  yaru-theme-gnome-shell
  yaru-theme-gtk
  yaru-theme-icon
  yaru-theme-sound
  yelp-xsl
  yelp
  zenity-common
  zenity
  zerofree
  zip
  zlib1g-dev
  zlib1g
)

echo "Installing ${#PACKAGES[@]} packages (--ignore-missing skips unavailable ones)..."
sudo apt-get install -y --ignore-missing "${PACKAGES[@]}"

echo "Installation complete!"
